# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/prabhanshu/projects/Multithreaded-HTTP-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/prabhanshu/projects/Multithreaded-HTTP-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prabhanshu/projects/Multithreaded-HTTP-Server/CMakeFiles /home/prabhanshu/projects/Multithreaded-HTTP-Server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prabhanshu/projects/Multithreaded-HTTP-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MultithreadedHTTPServer

# Build rule for target.
MultithreadedHTTPServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultithreadedHTTPServer
.PHONY : MultithreadedHTTPServer

# fast build rule for target.
MultithreadedHTTPServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/build
.PHONY : MultithreadedHTTPServer/fast

src/HttpParser.o: src/HttpParser.cpp.o
.PHONY : src/HttpParser.o

# target to build an object file
src/HttpParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpParser.cpp.o
.PHONY : src/HttpParser.cpp.o

src/HttpParser.i: src/HttpParser.cpp.i
.PHONY : src/HttpParser.i

# target to preprocess a source file
src/HttpParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpParser.cpp.i
.PHONY : src/HttpParser.cpp.i

src/HttpParser.s: src/HttpParser.cpp.s
.PHONY : src/HttpParser.s

# target to generate assembly for a file
src/HttpParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpParser.cpp.s
.PHONY : src/HttpParser.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/Router.o: src/Router.cpp.o
.PHONY : src/Router.o

# target to build an object file
src/Router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Router.cpp.o
.PHONY : src/Router.cpp.o

src/Router.i: src/Router.cpp.i
.PHONY : src/Router.i

# target to preprocess a source file
src/Router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Router.cpp.i
.PHONY : src/Router.cpp.i

src/Router.s: src/Router.cpp.s
.PHONY : src/Router.s

# target to generate assembly for a file
src/Router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Router.cpp.s
.PHONY : src/Router.cpp.s

src/Server.o: src/Server.cpp.o
.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i
.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s
.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultithreadedHTTPServer.dir/build.make CMakeFiles/MultithreadedHTTPServer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MultithreadedHTTPServer"
	@echo "... src/HttpParser.o"
	@echo "... src/HttpParser.i"
	@echo "... src/HttpParser.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/Router.o"
	@echo "... src/Router.i"
	@echo "... src/Router.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

